# Generated by Django 3.0.3 on 2020-03-17 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointKey', models.CharField(max_length=32, unique=True)),
                ('pointLabel', models.TextField()),
                ('point_id', models.CharField(max_length=32, unique=True)),
                ('commercialType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaspoints.CommercialType')),
            ],
        ),
        migrations.CreateModel(
            name='PointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sinonim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('root_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaspoints.Point')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='point',
            name='pointType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaspoints.PointType'),
        ),
    ]
