# Generated by Django 3.0.5 on 2020-04-16 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gaspoints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sinonim',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='point',
            name='commercialType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaspoints.CommercialType'),
        ),
        migrations.AddField(
            model_name='point',
            name='pointType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaspoints.PointType'),
        ),
        migrations.AddField(
            model_name='point',
            name='point_export_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaspoints.ExportCountry'),
        ),
        migrations.AddField(
            model_name='point',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
