# Generated by Django 3.0.5 on 2020-05-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaspoints', '0002_auto_20200519_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='exportcountry',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pointtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sinonim',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
