# Generated by Django 3.0.4 on 2020-04-03 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gaspoints', '0003_auto_20200320_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sinonim',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinonim',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
