# Generated by Django 3.0.4 on 2020-04-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaspoints', '0004_auto_20200403_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point_from_country',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='point_map_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='point_map_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
