# Generated by Django 3.0.4 on 2020-04-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaspoints', '0005_auto_20200410_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='point',
            name='point_from_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaspoints.FromCountry'),
        ),
    ]
