# Generated by Django 3.0.4 on 2020-04-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaspoints', '0009_remove_point_point_from_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FromCountry',
            new_name='From_Country',
        ),
    ]
