# Generated by Django 3.0.4 on 2020-04-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaspoints', '0011_auto_20200410_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportCountry',
        ),
    ]
