# Generated by Django 3.0.4 on 2020-04-10 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaspoints', '0013_exportcountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point_export_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gaspoints.ExportCountry'),
            preserve_default=False,
        ),
    ]
