# Generated by Django 3.0.4 on 2020-04-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaspoints', '0014_point_point_export_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='point_export_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaspoints.ExportCountry'),
        ),
    ]
