# Generated by Django 3.0.3 on 2020-03-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_user_app', '0002_remove_myuser_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_user_app.Place_of_job'),
            preserve_default=False,
        ),
    ]
